name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/workflows/install
      - name: Run lint and tests
        run: |
          pnpm run lint:ci
          pnpm run format:ci
          pnpm run typecheck
          pnpm run build
          pnpm run test
